### ISSUE TITLE
Unable to create resource for bundle mvn:no.priv.bang.sonar.sonar-collector/sonar-collector-webhook/1.5.22

### ISSUE THREAD

**Issue by westwind10** [steinarb/sonar-collector#5]
Hello,
I am writing to report an issue I encountered while trying to deploy the sonar-collector open-source project on Docker. Specifically, I received the following error message:

"org.apache.karaf.features.internal.util.MultiException: Error:
 Unable to create resource for bundle mvn:no.priv.bang.sonar.sonar-collector/sonar-collector-webhook/1.5.22
 at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)  ......
 "

I have attempted to troubleshoot this error but have been unable to find a solution. I believe this may be caused by a problem with the bundle resource, and I would greatly appreciate any assistance you can provide in resolving this issue.

Please let me know if there is any additional information I can provide to help diagnose the problem. Thank you for your attention to this matter.

**Comment by steinarb** [comment]
When was this? 

Last night about when?

I had some issues releasing 1.5.22 to maven central yesterday but when I tested later it seemed to have gone into maven central anyway and I have successfully installed in on my cloud server

Can you try doing the following
 1. Remove the sonar-collector from the local maven cache of the user karaf is running under
      ```
      rm -rf ~/.m2/repository/no/priv/bang/sonar/
      ```
 2. Try installing again

If that fails:

1. stop karaf
2. remove the karaf data directory
3. start karaf
4. reinstall sonar-collector (as well as anything else you may have running in karaf)

If you're running karaf from the debian package then steps 1-3 (stopping, deleting data, starting) can be done with
```
sudo apt reinstall karaf
```

**Comment by steinarb** [comment]
You can also explicitly install a version by replacing LATEST in the maven URL for the feature XML file with a particular version number (so you could e.g install 1.5.21 (only change to 1.5.22 is an older version of the PostgreSQL JDBC driver) or 1.5.20 (has an older version of liquibase))

**Comment by steinarb** [comment]
I wasn't aware this project has more users than myself.

Fun to hear! :smile:

**Comment by westwind10** [comment]
Thank you for your help. the problem has been resolved.🤗

**Comment by steinarb** [comment]
Good to hear! :smile: 

Out of curiousity: what did you do to fix it?

**Comment by westwind10** [comment]
Hello,
I still have some problem.😭
I deploy this project in docker like this:
  "docker run -p 8101:8101 -p 8181:8181 --name sonar_collector  -e "JDBC_URL=jdbc:postgresql://192.168.241.133:5432/sonar-collector"  -e "JDBC_USER=myuser" -e "JDBC_PASSWORD=sosecret" -d  --restart=always steinarb/sonar-collector"
And then execute command: "docker logs -f -t --tail 100 sonar_collector".

ERROR MESSAGE:
  "org.apache.karaf.features.internal.util.MultiException: Error:
 Unable to create resource for bundle mvn:no.priv.bang.sonar.sonar-collector/sonar-collector-webhook/1.5.22
 	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
 	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
 	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
 	at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
 	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
 	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 	at java.lang.Thread.run(Thread.java:748)
 	Suppressed: java.lang.Exception: Unable to create resource for bundle mvn:no.priv.bang.sonar.sonar-collector/sonar-collector-webhook/1.5.22
 		at org.apache.karaf.features.internal.region.Subsystem.createResource(Subsystem.java:824)
 		at org.apache.karaf.features.internal.region.Subsystem.lambda$downloadBundles$1(Subsystem.java:499)
 		at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.lambda$download$0(MavenDownloadManager.java:138)
 		at org.apache.karaf.features.internal.download.impl.DefaultFuture.notifyListener(DefaultFuture.java:350)
 		at org.apache.karaf.features.internal.download.impl.DefaultFuture.notifyListeners(DefaultFuture.java:335)
 		at org.apache.karaf.features.internal.download.impl.DefaultFuture.setValue(DefaultFuture.java:259)
 		at org.apache.karaf.features.internal.download.impl.AbstractDownloadTask.setFile(AbstractDownloadTask.java:61)
 		at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:61)
 		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 		... 3 more
 	Caused by: org.osgi.framework.BundleException: Unable to build resource for mvn:no.priv.bang.sonar.sonar-collector/sonar-collector-webhook/1.5.22: Importing java.* packages not allowed: java.io
 		at org.apache.felix.utils.resource.ResourceBuilder.build(ResourceBuilder.java:82)
 		at org.apache.felix.utils.resource.ResourceBuilder.build(ResourceBuilder.java:71)
 		at org.apache.karaf.features.internal.region.Subsystem.createResource(Subsystem.java:822)
 		... 14 more
 	Caused by: org.osgi.framework.BundleException: Importing java.* packages not allowed: java.io
 		at org.apache.felix.utils.resource.ResourceBuilder.normalizeImportClauses(ResourceBuilder.java:317)
 		at org.apache.felix.utils.resource.ResourceBuilder.doBuild(ResourceBuilder.java:176)
 		at org.apache.felix.utils.resource.ResourceBuilder.build(ResourceBuilder.java:80)
 		... 16 more
"
I feel helpless.😭

**Comment by steinarb** [comment]
I'm at work now and don't have access to my private development environment and that's the only place where I've ever run the docker image. 

And I haven't tried running the docker image for ages. 

Not sure if I can update it, either, since dockerhub removed their free tier? Maybe move it to github? They have a docker image registry now, I think...?

But anyway: I see what the problem probably is related to and that is Java version.

It's just that the problem seems to go the other way than I expected a docker-related issue like this to go: I would expect an old untouched docker image to keep running the Java version it was created with and this is the kind of error I would expecte to see when running a new Java version that has closed down exports more.

But I also see another problem and that is that the sonar-collector deployed to maven central has been built with Java 17 (for 2023 at least) and that is binary incompatible with Java 11 or Java 8 which is what the image probably is running (newer VMs can run binary code built with older version but not the other way around).

That can be worked around by creating a new docker image, based on my image (or simply by forking my repo) and replacing LATEST here with an explicit version from before I switched to java 17: https://github.com/steinarb/sonar-collector/blob/master/docker/docker/org.apache.karaf.features.cfg#L28

(Basically what I've done here is to take the standard karaf docker image and add the latest version of the sonar-collector, fetched from maven central, to the karaf boot features. This means I don't have to create a new docker image when I release a new version of sonar-collector, at the cost of the collector's startup time (because it has to download the jars from maven central at startup))

But I'll look at this when I get home and look at the possibility of creating an update (if newer versions of the official karaf docker image uses Java17 it should be possible. Also I need to be able to register the new docker image without having to pay to do so).

**Comment by steinarb** [comment]
Looking at the release history: https://github.com/steinarb/sonar-collector/tree/master?tab=readme-ov-file#release-history

Last Java 11 built version is 1.5.16 (from July 2 this year, so that was later than I remembered)

Last Java 8 built version is 1.4.7 (from October 14, 2021)

**Comment by westwind10** [comment]
Thank you for your reply, I will try again later.

**Comment by steinarb** [comment]
I see the same issue as you when trying to run the docker image locally.

Looks like the error messages are caused by OSGi version rather than Java version https://github.com/bndtools/bnd/issues/2507

The docker image uses OSGi 6, I think...? The newest sonar-collector is built with OSGi 8 (has been for quite a while, in fact).

**Comment by westwind10** [comment]
So how should I go about resolving this issue?
Clone the project, and then do this? https://www.eclipse.org/lists/osgi-dev/msg00093.html
Or edit Dockerfile to use Karaf 4.4.0?

**Comment by steinarb** [comment]
I would think that the only way is forward, and that the current version of sonar-collector runs fine on Java 17 and karaf 4.4.4 outside of docker, so...

I have tried to go to karaf 4.4.4 in docker here: https://github.com/steinarb/sonar-collector/tree/use-karaf-444-in-docker

But I ran into some weird problems trying to run the resulting image: my linux/amd64 build machine ended up with a linux/arm64 docker image somehow:
```
sb@lorenzo:~/workspaces/ws02/sonar-collector/docker$ docker run -p 8101:8101 -p 8181:8181  -e "JDBC_USER=dbuser" -e "JDBC_USER=verusecret" -d steinarb/sonar-collector:latest --platform linux/amd64
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
9aa30ce5b4c687f8f95e9e4b862d4826a1041ed211baa2ce594d8da26027376f
sb@lorenzo:~/workspaces/ws02/sonar-collector/docker$
```

(yeah, command should have had a JDBC_URL also, but I never got far enough to need it).

I have asked on the karaf mailing list, but no answers yet: https://lists.apache.org/list.html?user@karaf.apache.org
(the sonar-collector docker image is based on the official karaf docker-image and just modifies one file and adds two more... and now I remember that the karaf feature file needs to be updated as well for karaf 4.4.4 so I'll do that and push the changes).

In the case you have more luck than me in building the docker image, here is what you need to do:
```
git clone https://github.com/steinarb/sonar-collector.git
cd sonar-collector
git checkout use-karaf-444-in-docker
mvn clean install
cd docker
mvn clean install
```

**Comment by steinarb** [comment]
More changes related to karaf 4.4.4 has been pushed to https://github.com/steinarb/sonar-collector/tree/use-karaf-444-in-docker

The changes didn't help with the linux/arm64 issue (I didn't expect them to but it would be silly not to try).

But now, in theory, if you can get the right type of docker image, then things should run (except that the latest sonar-collector on maven central is built with Java 17 and the official karaf 4.4.4 image uses Java 11. That may still be an issue).

**Comment by steinarb** [comment]
If using Java 17 built sonar-collector on java 11 in the docker image is a problem, then swapping LATEST for 1.4.7 here, and then rebuilding the docker image should fix it: https://github.com/steinarb/sonar-collector/blob/b0d6cedb35648df11ef1554b9fb8fbe669e94640/docker/docker/org.apache.karaf.features.cfg#L29

You would be running an old version then, but there haven't been any code changes here that I can remember (it's a very simple application), just dependency upgrades and github actions build stuff.

**Comment by westwind10** [comment]
Thank you for your reply.
I  build docker image, and also get a linux/arm64 docker image.😭

**Comment by steinarb** [comment]
I'll give another spin at getting the correct docker image before I give up (there wasn't really much to go on from the error message and google didn't give me much info).

Another option open for you (_Note_: one that I won't go, but should be possible to do in a day or two), is to make a new unofficial karaf docker image and make that your basis:

1. Start with a plain debian 12 "bookworm" image (if you can find it? An Ubuntu image would probably work as well, but you should make sure that it is one that has Java 17 rather than java 11 or java 21. I know that the current debian stable (12.4 "bookworm") has java 17 as default, which is why I mentioned it)
2. [Use apt in this docker image to install karaf 4.4.4](https://steinar.bang.priv.no/2018/01/23/installing-apache-karaf-on-debian/)
3. Use this image as the basis for the pom I've used to make the docker image

Alternatively: if you have access to a non-docker, debian or ubuntu server: install the debian/APT package for karaf on that server and run sonar-collector there (that's how I run sonar-collector myself. Which is why the docker image has been left on its own for a couple of years...).

**Comment by westwind10** [comment]
Maybe I should install karaf on my server. I will start this work next week. 
Thank you very much, in any case.
Merry Christmas!

**Comment by steinarb** [comment]
Merry christmas! :santa: :christmas_tree: :gift: :snowman_with_snow: :candle:
